[options]
db_host = localhost
db_port = 5432
db_user = leopard1566
db_password = odoo
addons_path = /Users/leopard1566/Documents/GitHub/BSS_odoo/odoo17/addons,/Users/leopard1566/Documents/GitHub/BSS_odoo/bss_pocket_management,/Users/leopard1566/Documents/GitHub/BSS_odoo/odoo17_enterprise
without_demo = True

